# Generated by Django 2.2.12 on 2020-05-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_ispublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isPublished',
        ),
    ]
