# Generated by Django 2.2.12 on 2020-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
    ]
