# Generated by Django 2.2.12 on 2020-05-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_ispublished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='isPublished',
            new_name='is_published',
        ),
    ]
